### ISSUE TITLE
Delete latest old program

### ISSUE THREAD

**Issue by BlackWolf** [timoschlueter/RocketBeans.TV-Sendeplan#12]
Is there a specific reason why we keep the latest "old" program in the list? I find that rather confusing and would like to see the currently running program at the top of the list.

**Comment by der-tkw** [comment]
I was really uninspiration and checked how the browser extensions did it. They all keep up to 3 old programs in their list. It is planned that in the future the current program will be highlighted with a different background.

**Comment by BlackWolf** [comment]
I actually (rather unintentionally) removed this behaviour in #11 - it was kind of necessary since the way programs were added and removed caused issues if the google calendar returned unexpected values (this would cause ALL programs to appear in the app).

Since we both don't really see the point in keeping an old program I hope this is fine, otherwise I will have to change my pull request.

**Comment by der-tkw** [comment]
Hmm, #8 fixes all the strange cases Google delivers in their summary field. See comments in #9. @timoschlueter should decide what will happen :-)

**Comment by BlackWolf** [comment]
True. But as it is right now, if there is no "current" program this causes all programs to appear.
This is actually happening for me right now, since the google calendar seems to return only partial results.

**Comment by der-tkw** [comment]
The problem was actually that there was a gap in the calendar between 11:30 and 13:00. This should rather be handled correctly because I think this might happen more often than we think.

**Comment by TheVaan** [comment]
Maybe we can add an option screen later (for settings like notification of live show and so on) where the user can enable/disable "Show previous program in list".

The commit of #11 and #9 have been nearly at the same time... @timoschlueter should do a code review and decide which solution he like more :laughing:

**Comment by timoschlueter** [comment]
The browser extensions show at least one program from he past. I kind of like this concept since you know what you missed and what you should be looking for in the reruns or on youtube. 
But i have to admit: You guys totally lost me on this one for a second. Too many pull requests an issues at the same time on a sunday ;)

I merged #8 for now. Can someone please verify that everything still works? I don't see any errors on my side but i am a bit under the weather today.

**Comment by BlackWolf** [comment]
I guess it would be best to close #11 for now, I will just create a new pull request for the relative date thingy

**Comment by der-tkw** [comment]
I agree, so #11 and #12 should be closed.

**Comment by timoschlueter** [comment]
Okay. I opened issue #13 to discuss using ICS instead of XML in the future. I am currently looking into a way of using the ICS. As you guys already said: Using the XML may cause more problems in the future.
