### ISSUE TITLE
Send notification in case plan changes

### ISSUE THREAD

**Issue by der-tkw** [timoschlueter/RocketBeans.TV-Sendeplan#18]
The program plan changes often during the day, especially if there is not much information in the morning. Maybe we could store some kind of memento object and compare the new plan every minute against it. If it changes -> send a notification.

**Comment by timoschlueter** [comment]
Good idea! 
I often miss the plan updates myself. A reminder that a new shows have been added would be nice.

**Comment by timoschlueter** [comment]
Fixed in #22
