### ISSUE TITLE
Settings dialog opens in background

### ISSUE THREAD

**Issue by der-tkw** [timoschlueter/RocketBeans.TV-Sendeplan#23]
When first trying the settings I thought it didn't work. But after hiding all windows it appeared as the last dialog on my desktop.

**Comment by BlackWolf** [comment]
It seems that background applications cannot open windows in the foreground :/ See:

http://stackoverflow.com/questions/8479035/cocoa-put-window-in-the-foreground

Maybe there is a workaround, but so far I haven't found one

**Comment by RGPaul** [comment]
I wonder why the information window will appear on front and only the settings window is in background... is it because of the nswindowcontroller ?

**Comment by timoschlueter** [comment]
I haven't found a solution for this either. The code is the same as for the information window but the information window is not in its own xib.
I think @Manromen is right. It must be a problem with the window controller.

**Comment by timoschlueter** [comment]
Fixed in 445c79a.
