### ISSUE TITLE
Recurring events not listed

### ISSUE THREAD

**Issue by timoschlueter** [timoschlueter/RocketBeans.TV-Sendeplan#26]
The administrators of redditbeans switched to recurring events for some of the shows. This has the side effect that shows which have a recurring rule set don't show up in the app. For example: MoinMoin

The event in the ICS looks like this:

```
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20150202T103000
DTEND;TZID=Europe/Berlin:20150202T113000
RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
DTSTAMP:20150203T051002Z
UID:ou7lbi4igvvpn2f8feo7fo84bc@google.com
CREATED:20150131T125620Z
DESCRIPTION:
LAST-MODIFIED:20150131T125620Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:[L] MoinMoin
TRANSP:OPAQUE
END:VEVENT
```

The problem here is that the event is only stored once in the ICS and has the "RRULE" attribute set which then determines when the event should be listed.

To fix this, we have to check for the start- end enddate (like we already do with DTSTART and DTEND) and then check if today, tomorrow or the day after tomorrow matches the current date and create a event in the ProgramPlan after that. Another problem is that for single events, the DTSTART/DTEND is formatted as:

```
DTSTART:20150131T165500Z
```

Where in recurring events its formatted as:

```
DTSTART;TZID=Europe/Berlin:20150131T165500
```

So the date parsing and formatting has to be fixed too.

Since @BlackWolf is currently refactoring the code, i don't know if we should fix this right now or wait until he is ready?

**Comment by BlackWolf** [comment]
Sounds difficult :D Just go ahead, as long as this doesn't introduce some major structural changes it will be fine (I suppose it will mostly change the `parseICS()` method and some things about `ProgramPlan`, so that's fine).
I will add the new parsing to my refactoring, which I hope to commit later today (after work).

**Comment by timoschlueter** [comment]
It is more difficult than is thought :/ 
I reached out to the developer of the iOS app. Maybe he can share some insights about how he manages the Calendar data. I could try to fix it in a very ugly way but i don't think thats what we need. We should go for a reliable solution here.

**Comment by BlackWolf** [comment]
Yeah, I figured this would be difficult.

PS: There is an iOS app? want!

**Comment by timoschlueter** [comment]
There is: http://www.reddit.com/r/rocketbeans/comments/2u2kuy/meine_inoffizielle_rbtviphoneapp//
I am testing it right now. :)

I looked into Google Calendar API v3 as suggested by the developer of the iOS version. This would fix our problem since there is a flag which returns recurring events as single events. Unfortunately, i can't get the API key to work with the project. In the Google Developer Console, you can request an api-key for iOS which identifies your app using the Bundle Identifier. However, if i enter the Bundle Identifier of this app, it doesn't seem to work :/

**Comment by BlackWolf** [comment]
As far as I know, there are also "normal" Google API keys that are not bound to iOS, aren't they? I remember using one in a web-based project of mine, but it has been a while...

Unfortunately I won't have time to look into this further, I will hopefully commit the refactor later tonight, though (in case nothing broke).

**Comment by timoschlueter** [comment]
So, there it is. Replaced parseICS() with parseGoogleCalendar(). 
We are now using Google Calendar API V3, which unfortunately requires a API key. This key can be generated in the Google Developer Console (https://console.developers.google.com/project) and has to be associated with the Bundle Identifier of the App (which is: "in.timo.ios.RocketBeans-TV-Sendeplan"). Once you added your API key to the code, you should be able to receive data in the JSON format. 

I didnt fix anything else in this version and would appreciate it if someone could take the time and review the code.

**Comment by timoschlueter** [comment]
I screwed up the date comparing code. 
The app doesn't show the currently running show anymore. Hmm..

**Comment by timoschlueter** [comment]
Fixed in fe7a4530c1b2b3d51e6ec16b9e2f7adc2170c436

**Comment by BlackWolf** [comment]
Is the Google API key missing from the source by intention? It seems I cannot create my own, but as far as I understand the API key should be hardcoded into the source, shouldn't it?

**Comment by timoschlueter** [comment]
From what i understand, Google is not allowing people to share their API key. The key i generated is build into the binary where its not visible to the user. But putting it on github would violate the terms of Googles APIs, at least thats what i know.

Did you figure out how to generate your own key?
