### ISSUE TITLE
Feature request: Auf neue Version prüfen

### ISSUE THREAD

**Issue by hnrch02** [timoschlueter/RocketBeans.TV-Sendeplan#27]
Könnte man mit Hilfe der GitHub-API realisieren: https://api.github.com/repos/timoschlueter/RocketBeans.TV-Sendeplan/releases

Würde ja einen Pull Request senden, aber ich kenn mich mit Swift/Cocoa null aus.

**Comment by Manromen** [comment]
Da bin ich gerade dran.

**Comment by timoschlueter** [comment]
Da die App seit der neuen Version (>= 1.4.0) hauptsächlich über den App Store verteilt wird, erübrigt sich im Grunde dieses Feature request.
Ich denke auf den Update-Machanismus direkt in der App können wir dann verzichten, oder? :)

Link zum App Store: https://itunes.apple.com/de/app/sendeplan-fur-rocket-beans-tv/id1160411162?mt=12
