### ISSUE TITLE
Feature request: Setting für Aktualisierungsintervalle

### ISSUE THREAD

**Issue by pwndef** [timoschlueter/RocketBeans.TV-Sendeplan#28]
In den Settings sollte man selbst einstellen können, wann die App den Sendeplan aktualisiert. Vorzugsweise mit festgelegten Intervallen (z.B. 1 Min, 5 Min, 30 Min, 60 Min) oder zu einer festgelegten Uhrzeit.

**Comment by RGPaul** [comment]
Aber das gibt es doch schon .... nennt sich Updateinterval ....

**Comment by timoschlueter** [comment]
Diese Funktion gibt es wirklich schon. 
Daher schließe ich das hier mal :)
