### ISSUE TITLE
Font rendering bug on non-retina displays

### ISSUE THREAD

**Issue by BlackWolf** [timoschlueter/RocketBeans.TV-Sendeplan#30]
I tried to figure this out, but I can't: On non-retina displays, the main application seems to render text extremely strange as soon as we have a scrollbar in the timeplan.

What this means is that if I move the mouse over the application, the text starts to "jigger". Attached is a video of this: https://dl.dropboxusercontent.com/u/2282184/rbtvapp.mov

**Comment by timoschlueter** [comment]
Is this still an issue? I can't replicate this on my non-retina iMac.
