### ISSUE TITLE
Sometimes crashes when opening

### ISSUE THREAD

**Issue by xythobuz** [timoschlueter/RocketBeans.TV-Sendeplan#32]
Using the latest release (1.2.0), the app just crashed after clicking on its menu bar icon. [I've uploaded the Crash Report here](https://gist.github.com/xythobuz/441963d2c8a01eb00e61).

**Comment by xythobuz** [comment]
[Here is another Crash Report](https://gist.github.com/xythobuz/7c17ab6ceebb7d7ffd80), this time a segfault that happened while the App was idling.

And the first kind of crash, SIGILL upon opening the menu, has also happened again. [This Crash Report is here](https://gist.github.com/xythobuz/6e243cf6fb2330ca4721).

I hope it's not my computer at fault here, but your App is the only one that exhibits this behavior...

**Comment by timoschlueter** [comment]
I looked at the code yesterday. The problem seems to be the part where the received json-data is going to be return to the main thread of the application. I haven't experienced the problem myself yet but i would rule out that its a problem with your Mac.

**Comment by xythobuz** [comment]
The Sendeplan hasn't crashed in a long time, but today [it happened again](https://gist.github.com/xythobuz/855f07feba835a1c9a5f)... :smile:

**Comment by timoschlueter** [comment]
Should be fixed in Version 1.4.0 (https://github.com/timoschlueter/RocketBeans.TV-Sendeplan/releases/tag/1.4.0-beta.2).

**Comment by xythobuz** [comment]
Sadly I can't run the new beta on my Yosemite 10.10.5 machine. It seems to require at least El Capitan (10.11).

**Comment by timoschlueter** [comment]
My bad. I didnt pay attention to the target settings. 
I will archive a new binary as soon as i get home.

**Comment by timoschlueter** [comment]
Please test the new version, @xythobuz. 
I set the deployment target to 10.10. It should start now. 
https://github.com/timoschlueter/RocketBeans.TV-Sendeplan/releases/tag/1.4.0-beta.3

**Comment by xythobuz** [comment]
It starts now, first impression is great! 😄

**Comment by timoschlueter** [comment]
@xythobuz did you experience any crashes? If not, i would like to close this issue :)

**Comment by xythobuz** [comment]
Hasn't crashed since, looks good!

**Comment by timoschlueter** [comment]
Sounds good! :) I'm closing this issue. If it happens again, feel free to open a new one :)
