### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RGPaul** [timoschlueter/RocketBeans.TV-Sendeplan#33]
Könntest Du noch eine Lizenz beifügen? Vorzugsweise MIT oder Apache?
GPL oder so ist für mich auch in Ordnung, ich wüsste nur gerne zu was ich contribute. :-)

**Comment by timoschlueter** [comment]
Klar, habe meine favorisierte Lizenz (MIT) hinzugefügt.
Ärgerlich, dass ich anfangs vergessen habe :/
