### ISSUE TITLE
Change App Icons to RocketBeans.TV Icon

### ISSUE THREAD

**Issue by timoschlueter** [timoschlueter/RocketBeans.TV-Sendeplan#34]
We are currently using the RocketBeans "Company Logo" for the app. The stream itself uses the "RocketBeans.TV" Logo, which is the better way to go i think.

I found a high resolution logo on reddit, which we can used (i contacted the author of the reddit i found it in). Unfortunately, its a jpeg without transparency. Maybe someone has better graphical skills than i do an  can figure something out? 

Here is the logo from reddit: http://i.imgur.com/1qgG6gD.jpg

**Comment by TheVaan** [comment]
Does this logo come from a fan or is it made by the RocketBeans team?
Maybe we can get an original work file like psd or something similar. Or the creator can render a version with transparency.
Do you want to use this icon in the statusbar, too?

**Comment by timoschlueter** [comment]
I got it from [/u/thegamer93](https://www.reddit.com/user/thegamer93) on reddit. I already asked him for a PSD but he did not reponse so far.
Maybe we should ask the RocketBeans if they can provide the source files.

I think we should update the statusbar icon too. But i don't have the skills to convert the "new" one to  a good looking silhouette-style icon for the statusbar.

**Comment by TheVaan** [comment]
App icons changed with #36
