### ISSUE TITLE
Redditbeans.com ist eine Spam / Phishing Webseite!

### ISSUE THREAD

**Issue by Dak0r** [timoschlueter/RocketBeans.TV-Sendeplan#41]
Hey,
Du hast in deiner Readme die Seite Redditbeans.com erwähnt, aber diese Seite führt nur zu einer Phishing Webseite.

**Comment by RGPaul** [comment]
Das müsste Redditbeans.de sein.

**Comment by timoschlueter** [comment]
Shit, das ist nicht gut - und war natürlich keine Absicht! :/
Gefixt in 1769694c9c468576ead4698d4ed6841cb707c2e2
Danke für den Hinweis!
