### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by badrabbit** [timoschlueter/RocketBeans.TV-Sendeplan#42]
Wird die App hier noch weitergeführt? Eine aktuelle Version mit Stabilisierungen und dem neuen Youtube-Stream wären klasse. Vielen Dank für die bisherige Arbeit!

**Comment by timoschlueter** [comment]
Danke für das Feedback, @badrabbit. :)
Es steht noch auf dem Plan die App zu aktualisieren, aber leider gibt mein Vollzeitjob das aktuell nicht her.
Wenn sich jemand dem Projekt annehmen möchte: Ich erteile gerne volle Rechte auf das Repository :)

**Comment by timoschlueter** [comment]
Ich habe mit einer neuen Version basierend auf Swift 3.0 begonnen. 

Da die App in Zukunft die offizielle Sendeplan-API verwenden soll, war es für mich einfacher, die App von Grund auf neu aufzubauen. Es fehlen allerdings noch das Notification Center Widget und die Benachrichtigungen.
Ich werde versuchen, in den nächsten Tagen die neue Version hier im Quellcode zu veröffentlichen. Zeitlich ist das leider gerade alles etwas schwierig :/

Die Weiterentwicklung gestaltet sich allerdings angesichts der benutzerspezifischen API-Zugangsdaten als etwas schwieriger. Jeder, der an der App weiter mitentwickeln möchte, muss sich von Rocket Beans TV (genauer gesagt Max) Zugangsdaten für die API schicken lassen. (Looking at you, @TheVaan, @Manromen, @BlackWolf, @timbooo ;))

**Comment by RGPaul** [comment]
Hallo Timo,
ich bin gerade beruflich etwas eingespannt, werde aber versuchen mit zu partizipieren.

**Comment by TheVaan** [comment]
Hallo zusammen!

Bin auch gerade Beruflich eingespannt, aber ich werde mir mal nen API Key schicken lassen und mir die Geschichte anschauen. Mal schauen, ob ich dann etwas dazu beitragen kann.

**Comment by timoschlueter** [comment]
Ich habe angefangen. Der neue Code befindet sich in einer neuen Branch a5cb8996c397aa079068295444ce1bc05849e013.

Derzeit wird nur der Sendeplan von der offiziellen API geladen und angezeigt. Notifications, Live-Icon etc. fehlen derzeit noch.

Bezüglich der API-Zugangsdaten: Wenn ihr eure Daten von Max bekommen habt, könnt ihr sie an folgender Stelle hinterlegen:

https://github.com/timoschlueter/RocketBeans.TV-Sendeplan/blob/official-api-rewrite/Sendeplan%20fuer%20Rocket%20Beans%20TV/ProgramPlan.swift#L50

Falls ihr also Zeit und Lust habt, könnt ihr gerne loslegen. Bitte verewigt euch auch im "Informationen"-Window mit euren Social Media Profilen etc., sofern ihr möchtet. Sollte die App vernünftig laufen, könnte ich mir vorstellen sie dieses Mal in den App Store zu stellen. Allerdings möchte ich dann nicht, dass jemand von euch unter "Credits" unerwähnt bleibt :)

**Comment by timoschlueter** [comment]
Mit c17052c3f90511358aa44a6da8ad4d190c7629b5 ist das Today View Widget wieder dazu gekommen.

**Comment by timoschlueter** [comment]
Erste (lauffähige) Version kann hier geladen werden: https://github.com/timoschlueter/RocketBeans.TV-Sendeplan/releases/tag/1.4.0-beta.1 

Ich schließe damit erstmal diese Issue. Die Weiterentwicklung passiert dann über den üblichen Weg :)

**Comment by BlackWolf** [comment]
Ich weiß der Spruch wird alt, aber aktuell gibt's meine Freizeit leider nicht her. Ab November bin ich aber wieder etwas freier und helfe dann gerne aus soweit ich kann :-)

Aber toll das die App noch weiterentwickelt wird, ich mache sobald ich kann gerne wieder mit!
