### ISSUE TITLE
Kein Sendeplan mehr

### ISSUE THREAD

**Issue by badrabbit** [timoschlueter/RocketBeans.TV-Sendeplan#56]
Sendeplan-Anzeige bleibt leer.

<img width="1280" alt="bildschirmfoto 2018-03-14 um 17 48 04" src="https://user-images.githubusercontent.com/78358/37417364-5e384828-27b0-11e8-8e51-947186f7edd7.png">
App 1.6.0 (App Store Version)
macOS 10.13.4. beta

**Comment by timoschlueter** [comment]
Das SSL-Zertifikat der Rocket Beans Sendeplan API ist abgelaufen:

<img width="499" alt="bildschirmfoto 2018-03-14 um 18 12 21" src="https://user-images.githubusercontent.com/3465220/37419703-5a6e1b1e-27b5-11e8-8cf4-0c50a1787ce6.png">

Ich habe Max (von RBTV) bereits informiert. Er gibt das Problem weiter. Ein Update der App wird in diesem Fall nicht notwendig sein. Ich lasse die Issue offen, bis das Problem endgültig behoben wurde.

**Comment by timoschlueter** [comment]
Das Problem wurde soeben behoben:

<img width="441" alt="bildschirmfoto 2018-03-14 um 18 50 01" src="https://user-images.githubusercontent.com/3465220/37421008-8a695290-27b8-11e8-8084-edaf5a8e7b89.png">

Ggf. einmal die App neu starten, sollte es noch Probleme geben.

**Comment by badrabbit** [comment]
macOS 10.13.5
letzte MacApp-Store Version
Lässt sich nicht mehr starten und erscheint nicht mehr in der Menüleiste. Neuinstallation brachte keine Besserung.

Wird die App noch aktualisiert (Dez. 2016)?
