### ISSUE TITLE
Calculation fails when program overlaps midnight

### ISSUE THREAD

**Issue by der-tkw** [timoschlueter/RocketBeans.TV-Sendeplan#7]
In case a program overlaps midnight the feed internally returns "Sa 24. Jan. 2015 23:30 bis 00:05" which is used to calculate everything. However it should be "Sa 24. Jan. 2015 23:30 bis So 25. Jan. 2015 00:05" as it says in the summary when visiting the google calendar directly in order to work. We need some kind of workaround for that.

**Comment by TheVaan** [comment]
I think that could probably be a kind of GMT problem. In GMT the program starts at 22:30 and ends at 23:05.

**Comment by der-tkw** [comment]
Sounds reasonable. I added a comparison for the start and end date, and in case end < start I just add another day to it to maintain the algorithm.
